<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_OrderInformation
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
$helper = $block->getData('bookingHelper');
$_productCollection = $block->getLoadedProductCollection();
$bookingInfoArray = [];
foreach ($_productCollection as $product) {
    $isBooking = $helper->isBookingProduct($product->getId());
    $productUrl = $product->getProductUrl();
    $bookingInfoArray[$productUrl]['booking'] = $isBooking;
}
$serializedFormData = $helper->getSerializedString(["bookingInfoArray" => $bookingInfoArray]);
?>
<script type="text/x-magento-init">
    {
        "body": {
            "Mavenbird_BookingSystem/js/bookingsystem": <?= /* @noEscape */ $serializedFormData ?>
        }
    }
</script>
