<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_OrderInformation
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<script id="calendar-template" type="text/x-magento-template">
    <div class='wk-box-modal'>
        <div class='wk-box-modal-bg'>
            <div class='wk-loader'></div>
        </div>
        <div class='wk-modal-head'>
            <span><?= $escaper->escapeHtml(__('Select Slot To Book')); ?></span>
        </div>
        <div class='wk-modal-body'>
            <div class='wk-wrapper'>
                <div class='wk-calendar-container'>
                    <div class='wk-booking-table wk-calendar-table'>
                    </div>
                </div>
                <div class='wk-day-container'>
                    <div class='wk-booking-table'>
                        <div class='wk-booking-table-head'>
                            <div class='wk-selected-date-wrapper'>
                                <div class='wk-selected-date'></div>
                                <div class='wk-selected-month-day'>
                                    <div class='wk-month'></div>
                                    <div class='wk-selected-day'></div>
                                </div>
                            </div>
                        </div>
                        <div class='wk-booking-table-body'>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class='wk-modal-foot'>
            <div class='wk-notation-wrapper'>
                <label class='label'>Notation</label>
                <div class='noations-group'>
                    <span class='available-slots notation-slots'>
                        <?= $escaper->escapeHtml(__('Available Slots')); ?>
                    </span>
                    <span class='not-available-slots notation-slots'>
                        <?= $escaper->escapeHtml(__('Unavailable Slots')); ?>
                    </span>
                    <span class='already-booked-slots notation-slots'>
                        <?= $escaper->escapeHtml(__('Booked Slots')); ?>
                    </span>
                </div>
            </div>
            <div class='wk-slots-summary-wrapper' style='display:none'>
                <div class='slots-summary'>
                    <label class='label'><?= $escaper->escapeHtml(__('Summary')); ?></label>
                    <div class='booked-slot-summary'></div>
                </div>
                <div class='add cart button'>
                    <button type='button' class='wk-book action tocart primary'>
                        <?= $escaper->escapeHtml(__('Book Now')); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Mavenbird_BookingSystem/js/create-admin-order": {
                "getCalenderUrl": "<?= $escaper->escapeUrl($block->getUrlCustom()) ?>"
            }
        }
    }
</script>