<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_OrderInformation
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Book Now'); ?>
<?php
$productId = $_product->getId();
$helper = $block->getData('bookingHelper');
$cartHelper = $helper->getCartHelper();
$helper->getCurrentTimeZone();
if ($block->getRequest()->getRouteName() == "wishlist") {
    $options = $helper->getProductOptions($block->getRequest()->getParam('product_id'));
} else {
    $options = $helper->getProductOptions($productId);
}
$url = $cartHelper->getAddUrl($_product);
$bookingInfo = $helper->getBookingInfo($productId);
$bookingType = $bookingInfo['type'];
$preventBookingBefore = $bookingInfo['prevent_booking_before']??'';
$formKey = $helper->getFormKey();
$formatedSlots = $helper->getFormattedSlots($productId);
$parentId = $helper->getParentSlotId($productId);
$headerTitles = [__('Date'), __('Day'), __('Slot Time'), __('No. of Slots'), ''];
$data =  $helper->getSerializedString([
    "slots" => $formatedSlots,
    "parentId" => $parentId,
    "formKey" => $formKey,
    "productId" => $productId,
    "options" => $options,
    "slotsUrl" => $block->getUrl('bookingsystem/booking/slots'),
    "cartUrl" => $url,
    "removeUrl" => $block->getUrl('bookingsystem/booking/remove'),
    "booking_type" => $bookingType,
    "prevent_booking_before" => $preventBookingBefore
]);
?>
    <div class="wk-bg-container">
        <div class="wk-box-modal">
            <div class="wk-box-modal-bg">
                <div class="wk-loader"></div>
            </div>
            <div class="wk-modal-head">
                <div class="wk-close">X</div>
                <?= $escaper->escapeHtml(__("Select Slot To Book")); ?>
            </div>
            <div class="wk-modal-body">
                <div class="wk-wrapper">
                    <div class="wk-calendar-container">
                        <div class="wk-booking-table wk-calendar-table">
                            <?= /** @noEscape */ $helper->getAllCalendars($productId); ?>
                        </div>
                    </div>
                    <div class="wk-day-container">
                        <div class="wk-booking-table">
                            <div class="wk-booking-table-head">
                                <div class="wk-selected-date-wrapper">
                                    <div class="wk-selected-date"></div>
                                    <div class="wk-selected-month-day">
                                        <div class="wk-month"></div>
                                        <div class="wk-selected-day"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="wk-booking-table-body">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="wk-modal-foot">
                <div class="wk-notation-wrapper">
                    <label class="label"><?= $escaper->escapeHtml(__("Notation")) ?></label>
                    <div class="noations-group">
                        <span class="available-slots notation-slots">
                            <?= $escaper->escapeHtml(__("Available Slots")) ?>
                        </span>
                        <span class="not-available-slots notation-slots">
                            <?= $escaper->escapeHtml(__("Unavailable Slots")) ?>
                        </span>
                        <span class="already-booked-slots notation-slots">
                            <?= $escaper->escapeHtml(__("Booked Slots")) ?>
                        </span>
                    </div>
                </div>
                <div class="wk-slots-summary-wrapper" style="display:none">
                    <div class="slots-summary">
                        <label class="label"><?= $escaper->escapeHtml(__("Summary ")) ?></label>
                        <div class="booked-slot-summary"></div>
                    </div>
                    <div class="add cart button">
                        <button type="button" class="wk-book action tocart primary">
                            <?= $escaper->escapeHtml(__("Book Now")); ?>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <div class="actions">
            <button id="wk-book-now"
                type="button"
                title="<?= $escaper->escapeHtml($buttonTitle) ?>"
                class="wk-book-now action primary tocart">
                <span><?= $escaper->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "body": {
            "Mavenbird_BookingSystem/js/bookingsystem": <?= /* @noEscape */ $data ?>
        }
    }
</script>
